# Nombre del paquete
package_name: model-flights-delays

# Archivos de datos
train_data_file: train.csv
test_data_file: test.csv

# Variables
# Objetivo
target: DepDel15

features:
  - Month
  - DayOfWeek
  - DestAirportID
  - AirportID
  - Day
  - Visibility
  - DryBulbCelsius
  - WetBulbCelsius
  - DewPointCelsius
  - RelativeHumidity
  - WindSpeed
  - WindDirection
  - StationPressure
  - Altimeter
  - AA
  - SP
  - SY-MT

# pipelines
pipeline_name: model-flights-delays
pipeline_save_file: model-flights-delays-output

# fracción del conjunto de prueba
test_size: 0.25

# semilla
random_state: 42

# hiperparámetros del modelo 
n_estimators: 100
max_depth: 3
max_features: sqrt
loss: exponential
learning_rate: 0.05
